title: Wayne Boka, Web Developer
author: Wayne Boka
email: wayne@bokasolutions.com
description: >- # this means to ignore newlines until "baseurl:"
  Wayne Boka is a web developer based in Westfield, PA. He works
  with a variety of technologies including ColdFusion, JavaScript,
  HTML, CSS, Django, and Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wboka.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wtboka
github_username:  wboka
website: https://www.bokasolutions.com
rss: RSS

# Excerpts
excerpt_separator: <!--more-->
show_excerpts: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      author: Wayne Boka


# Paginatation
# paginate: 5
# paginate_path: "/:num/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
